RunGroopWebApp/Models/Club.cs
using RunGroopWebApp.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunGroopWebApp.Models
{
    public class Club
    {
        [Key]
        public int Id { get; set; } 
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address? Address { get; set; }
        public ClubCategory ClubCategory { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

RunGroopWebApp/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroopWebApp.Data;
using RunGroopWebApp.Interfaces;
using RunGroopWebApp.Models;

namespace RunGroopWebApp.Controllers
{
    public class ClubController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IClubRepository _clubRepository;
        public ClubController(ApplicationDbContext context,IClubRepository clubRepository)
        {
            _context = context;
            _clubRepository = clubRepository;
        }
        public async Task<IActionResult> Index()
        {
            var clubs = await _clubRepository.GetAll();
            return View(clubs);
        }

        [HttpPost]
        public async Task<IActionResult> Detail(int id)
        {
            Club club = await _clubRepository.GetById(id);
            return View(club);

        }
        public async Task<IActionResult> Create(Club club)
        {
            if (ModelState.IsValid) 
            {
                return View(club);
            }
            _clubRepository.Add(club);
            return RedirectToAction("Index");
        }
    }
}

RunGroopWebApp/Views/Club/Index.cshtml
@model IEnumerable<Club>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<ul class="row feature-list feature-list-sm">
    @foreach (var club in Model)
    {
        <li class="col-12 col-md-6 col-lg-4">
            <div class="card">
                <a type="button" asp-controller="Club" asp-action="Detail" asp-route-id="@club.Id">
                    <img class="card-img-top" src="@club.Image" alt="Card image cap">
                </a>
                <div class="card-body">
                    <h4 class="card-title">@club.Title</h4>
                    <p class="card-text">@club.Description</p>
                </div>
                <div class="card-footer card-footer-borderless d-flex justify-content-between">
                    <div>
                        <small>@club.ClubCategory</small>
                    </div>
                </div>
                <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@club.Id"
                    class="btn btn-sm btn-outline-secondary">View</a>
            </div>
        </li>
    }
</ul>